// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
static struct state s_state = {0, 100, 0, 5000, "P", 0, 0, 0, 150, 10, 0, false, false, false, false, false, false, false, false, false, false, true, false, "Comfort"};
void glue_get_state(struct state *data) {
  *data = s_state;  // Sync with your device
}
void glue_set_state(struct state *data) {
  s_state = *data; // Sync with your device
}

static uint64_t s_action_timeout_steering_button_pressed;  // Time when steering_button_pressed ends
bool glue_check_steering_button_pressed(void) {
  return s_action_timeout_steering_button_pressed > mg_now(); // Return true if steering_button_pressed is in progress
}
void glue_start_steering_button_pressed(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_steering_button_pressed = mg_now() + 1000; // Start steering_button_pressed, finish after 1 second
}

static struct login s_login = {"", ""};
void glue_get_login(struct login *data) {
  *data = s_login;  // Sync with your device
}
void glue_set_login(struct login *data) {
  s_login = *data; // Sync with your device
}

